version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - hex-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        user: "1000:1000"
        container_name: app
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app:rw
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - hex-network
    mariadb:
        image: mariadb
        container_name: mariadb
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: aws-test
        networks:
            - hex-network

    storage:
        image: minio/minio
        container_name: storage
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio:/data:rw
        environment:
            - "MINIO_ROOT_USER=root"
            - "MINIO_ROOT_PASSWORD=password"
        command: server --console-address ":9001" /data/
        networks:
            - hex-network

    storage-mc:
        image: minio/mc
        command:
            - mc mb hex-bucket
        depends_on:
            - storage
        container_name: storage-mc
        volumes:
            - minio:/minio:rw
        networks:
            - hex-network

networks:
    hex-network:
        driver: bridge

volumes:
    minio:
